import '@assets/styles/globals.scss'
import Container from '@components/organisms/Container'
import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'

const inter = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: 'SQOUTS',
    template: '%s | SQOUTS',
  },
  description: 'Generated by create next app',
  icons: [{ url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>{children}</Container>
      </body>
    </html>
  )
}
